export const places: Record<string, string[]> = {
  sa: ["Rio de Janeiro", "Cusco", "São Paulo", "Lima", "Santiago"],
  asia: [
    "Kuta",
    "Kuala Lumpur",
    "Danang",
    "Siem Reap",
    "Ho Chi Minh City",
    "Hanoi",
    "Colombo",
    "Nuwara Eliya",
    "Kandy",
    "Bangkok",
    "Singapore",
    "Seoul",
    "Galle",
    "Bentota",
    "Anuradhapura",
    "Phuket",
    "Agra",
    "Phnom Penh",
    "Yogyakarta",
    "Tokyo",
    "Varanasi",
    "Hue",
    "Kota Kinabalu",
    "Chiang Mai",
    "Sigiriya",
    "Lombok",
    "Kyoto",
    "Krabi",
    "Nha Trang",
    "Beijing",
    "Osaka",
    "Jakarta",
    "Kuching",
    "Yala",
    "Pattaya",
    "Coron",
  ],
  carribbean: ["Montego Bay", "Ocho Rios", "Punta Cana", "Negril", "Kingston"],
  europe: [
    "Rome",
    "London",
    "Paris",
    "Barcelona",
    "Lisbon",
    "Cascais",
    "Florence",
    "Sorrento",
    "Capri",
    "Naples",
    "Amsterdam",
    "Madrid",
    "Prague",
    "Berlin",
    "Venice",
    "Athens",
    "Budapest",
    "Salerno",
    "Istanbul",
    "Portimão",
    "Lagos",
    "Seville",
    "Vienna",
    "Dubrovnik",
    "Reykjavík",
    "Milan",
    "Como",
    "Porto",
    "Krakow",
    "Split",
    "Hamburg",
    "Cannes",
    "Nice",
    "Faro",
    "Edinburgh",
    "Dublin",
    "Málaga",
    "Tbilisi",
    "Munich",
    "Stockholm",
    "Bucharest",
    "Verona",
    "Bologna",
    "Granada",
    "Valencia",
    "Marseille",
    "Antalya",
    "Brussels",
    "Warsaw",
    "Funchal",
    "Ljubljana",
    "Siena",
    "Cologne",
    "Bordeaux",
    "Sofia",
    "Rotterdam",
    "The Hague",
    "Zagreb",
    "Salzburg",
    "Düsseldorf",
    "Side",
    "Copenhagen",
    "Riga",
    "Liverpool",
    "Pisa",
    "Bristol",
    "Lucca",
    "Las Palmas de Gran Canaria",
    "Córdoba",
    "Bratislava",
    "York",
    "Kotor",
    "Leeds",
    "Podgorica",
    "Assisi",
    "Perugia",
    "Lyon",
    "Bath",
    "Bonn",
    "Rethymno",
    "Oslo",
    "Helsinki",
    "San Sebastián",
    "Bilbao",
    "Dresden",
    "Glasgow",
    "Bruges",
    "Belfast",
    "Chania International Airport",
    "Heidelberg",
    "Oxford",
    "Catania",
    "Frankfurt",
    "Vilnius",
    "Avignon",
    "Turin",
    "Tallinn",
    "Ibiza Town",
    "Inverness",
    "Rovaniemi",
    "Wrocław",
    "Genoa",
    "Galway",
    "Cardiff",
    "Ponta Delgada",
    "Thessaloniki",
    "Paphos",
    "Stuttgart",
    "Alanya",
    "Bari",
    "Sarajevo",
    "Mikonos",
    "Corfu",
    "Girona",
    "Alicante",
    "Manchester",
    "Reims",
    "Cambridge",
    "Skopje",
    "Zurich",
    "Zadar",
    "Geneva",
    "Lecce",
    "Portorož",
    "Parma",
    "Brighton & Hove",
    "Gdańsk",
    "Innsbruck",
    "Marbella",
    "Chişinău",
    "Tromsø",
    "Tarragona",
    "Pula",
    "Coimbra",
    "Palermo",
    "Cádiz",
    "Nuremberg",
    "Bergen",
    "Lausanne",
    "Montpellier",
    "Rhodes Town",
    "Akureyri",
    "Newcastle upon Tyne",
    "Tours",
    "Birmingham",
    "Plovdiv",
    "Strasbourg",
    "Malmö",
    "Ghent",
    "Colmar",
    "Cork",
    "Odesa",
    "Utrecht",
    "Toulouse",
  ],
  oceania: [
    "Melbourne",
    "Sydney",
    "Fremantle",
    "Perth",
    "Cairns",
    "Gold Coast",
    "Adelaide",
    "Hobart",
    "Brisbane",
    "Darwin",
    "Auckland",
    "Port Douglas",
    "Byron Bay",
    "Airlie Beach",
    "Ayers Rock",
    "Margaret River",
    "Launceston",
  ],
  africa: [
    "Cairo",
    "Marrakesh",
    "Hurghada",
    "Luxor",
    "Fez",
    "Nairobi",
    "Aswan",
    "Agadir",
    "Sharm El Sheikh",
    "Marsa Alam",
    "Cape Town",
    "Accra",
    "Arusha",
    "Casablanca",
    "Midlands",
    "Essaouira",
    "Dahab",
    "Alexandria",
    "Tangier",
    "Zanzibar City",
  ],
  na: [
    "New York",
    "Cancún",
    "Las Vegas",
    "New Orleans",
    "San Francisco",
    "Los Angeles",
    "Washington, D.C.",
    "Miami",
    "San José del Cabo",
    "Cozumel",
    "Playa del Carmen",
    "Chicago",
    "Boston",
    "Mexico City",
    "Orlando",
    "Kissimmee",
    "Savannah",
    "San Diego",
    "Puerto Vallarta",
    "Key West",
    "Tulum",
    "Portland",
    "Denver",
    "Flagstaff",
    "Sedona",
    "Philadelphia",
    "Nashville",
    "Phoenix",
    "Scottsdale",
    "Tampa",
    "Seattle",
    "San Antonio",
    "Honolulu",
    "Fort Lauderdale",
    "St. Augustine",
    "Dallas",
    "Atlanta",
    "Branson",
    "Naples",
    "Vancouver",
    "Oaxaca City",
    "Guadalajara",
    "Anchorage",
    "Santa Barbara",
    "Niagara Falls",
    "Baltimore",
    "Cincinnati",
    "Mérida",
    "Montreal",
    "Toronto",
    "Richmond",
    "Jackson",
    "Tusayan",
    "Fairbanks",
    "Hartsville",
    "Santa Cruz Huatulco",
    "Sarasota",
  ],
  middleEast: [
    "Dubai",
    "Abu Dhabi",
    "Ras al Khaimah",
    "Amman",
    "Beirut",
    "Tel Aviv",
    "Muscat",
    "Jerusalem",
    "Aqaba",
    "Doha",
    "Salalah",
    "Riyadh",
  ],
};

export function randomRoll(continent: string) {
  const randomIndex = Math.floor(Math.random() * places[continent].length);
  return places[continent][randomIndex];
}

const lowerCasedPlaces: Record<string, string[]> = Object.keys(places).reduce(
  (acc, continent) => {
    acc[continent] = places[continent].map((place) => place.toLowerCase());
    return acc;
  },
  {} as Record<string, string[]>
);

export function isAGoodPlace(placeString: string) {
  for (const region of Object.keys(places)) {
    if (lowerCasedPlaces[region].includes(placeString.toLowerCase())) {
      return true;
    }
  }
  return false;
}
