export const places = {
  sa: ["Rio de Janeiro", "Cusco", "S\u00e3o Paulo", "Lima"],
  asia: [
    "Ubud",
    "Seminyak",
    "Kuta",
    "Nusa Dua",
    "Jimbaran",
    "Kuala Lumpur",
    "Danang",
    "Hoi An",
    "Siem Reap",
    "Ho Chi Minh City",
    "Hanoi",
    "Colombo",
    "Nuwara Eliya",
    "Kandy",
    "Bangkok",
    "Singapore",
    "Seoul",
    "Galle",
    "Bentota",
    "Anuradhapura",
    "Ko Yao Yai",
    "Phuket",
    "Penaga",
    "Agra",
    "Phnom Penh",
    "Yogyakarta",
    "Tokyo",
    "Varanasi",
    "Hue",
    "Kota Kinabalu",
    "Chiang Mai",
    "Sigiriya",
    "Negombo",
    "Lombok",
    "Kyoto",
    "Krabi",
    "Pulau Langkawi",
    "Cebu City",
  ],
  carribbean: [
    "Montego Bay",
    "Stepney",
    "Runaway Bay",
    "Ocho Rios",
    "Punta Cana",
    "Negril",
  ],
  europe: [
    "Rome",
    "London",
    "Paris",
    "Barcelona",
    "Lisbon",
    "Sintra",
    "Cascais",
    "Florence",
    "Pompei",
    "Sorrento",
    "Capri",
    "Naples",
    "Amsterdam",
    "Madrid",
    "Prague",
    "Berlin",
    "Potsdam",
    "Venice",
    "Athens",
    "Arma\u00e7\u00e3o de P\u00eara",
    "Albufeira",
    "Budapest",
    "Salerno",
    "Istanbul",
    "Portim\u00e3o",
    "Lagos",
    "Seville",
    "Vienna",
    "Dubrovnik",
    "Lecco",
    "Reykjav\u00edk",
    "Milan",
    "Como",
    "Porto",
    "Krakow",
    "Split",
    "Hamburg",
    "Cannes",
    "Nice",
    "Faro",
    "Edinburgh",
    "Dublin",
    "M\u00e1laga",
    "Tbilisi",
    "Munich",
    "Poris de Abona",
    "Stockholm",
    "Bucharest",
    "Verona",
    "Garda",
    "Bologna",
    "Modena",
    "Granada",
    "Valencia",
    "Marseille",
    "G\u00f6reme",
    "Aix-en-Provence",
    "Antalya",
    "Brussels",
    "Warsaw",
    "Funchal",
    "Ljubljana",
    "Siena",
    "Cologne",
    "San Gimignano",
    "Bordeaux",
    "Sofia",
    "Rotterdam",
    "The Hague",
    "Zagreb",
    "Salzburg",
    "D\u00fcsseldorf",
    "Sol de Mallorca",
    "Side",
    "Copenhagen",
    "Riga",
    "Liverpool",
    "Pisa",
    "Emporio Santorini",
    "Bristol",
    "Lucca",
    "Las Palmas de Gran Canaria",
    "C\u00f3rdoba",
    "Bra\u015fov",
    "Bratislava",
    "York",
    "Kotor",
    "Leeds",
    "Podgorica",
    "Assisi",
    "Perugia",
    "Lyon",
    "Bath",
    "Bonn",
    "Rethymno",
    "Oslo",
    "Helsinki",
    "San Sebasti\u00e1n",
    "Bilbao",
    "Dresden",
    "Glasgow",
    "Bovec",
    "Bruges",
    "Bled",
    "Belfast",
    "Schwetzingen",
    "Chania International Airport",
    "Heidelberg",
    "Oxford",
    "Catania",
    "Frankfurt",
    "Vilnius",
    "Avignon",
    "Turin",
    "Tallinn",
    "Ibiza Town",
    "Ku\u015fadas\u0131",
    "Marmaris",
    "Inverness",
    "Rovaniemi",
    "Wroc\u0142aw",
    "Genoa",
    "Galway",
    "Cardiff",
    "Ponta Delgada",
    "S\u00e3o Roque",
    "Thessaloniki",
    "Paphos",
    "Stuttgart",
    "Benidorm",
    "Fethiye",
  ],
  oceania: [
    "Melbourne",
    "Sydney",
    "Fremantle",
    "Perth",
    "Cairns",
    "Gold Coast",
    "Adelaide",
    "Hope Valley",
    "Hobart",
    "Noosa Heads",
    "Brisbane",
    "Darwin",
    "Auckland",
  ],
  africa: [
    "Cairo",
    "Marrakesh",
    "Hurghada",
    "Luxor",
    "Fez",
    "Nairobi",
    "Aswan",
    "Agadir",
    "Sharm El Sheikh",
    "Marsa Alam",
    "Cape Town",
    "Accra",
    "Arusha",
    "Casablanca",
  ],
  na: [
    "New York",
    "Canc\u00fan",
    "Las Vegas",
    "New Orleans",
    "San Francisco",
    "Los Angeles",
    "Washington, D.C.",
    "Miami",
    "San Jos\u00e9 del Cabo",
    "Cabo San Lucas",
    "Cozumel",
    "Playa del Carmen",
    "Chicago",
    "Boston",
    "Mexico City",
    "Orlando",
    "Kissimmee",
    "Kahuku",
    "Savannah",
    "San Diego",
    "Puerto Vallarta",
    "Kapalua West Maui Airport",
    "Key West",
    "Tulum",
    "Portland",
    "Denver",
    "Flagstaff",
    "Sedona",
    "Philadelphia",
    "Nashville",
    "Phoenix",
    "Scottsdale",
    "Tampa",
    "Seattle",
    "San Antonio",
    "Honolulu",
    "Fort Lauderdale",
    "St. Augustine",
    "Dallas",
    "Atlanta",
    "Branson",
    "Naples",
    "Vancouver",
    "Oaxaca City",
  ],
  middleEast: [
    "Dubai",
    "Abu Dhabi",
    "Ras al Khaimah",
    "Amman",
    "Beirut",
    "Tel Aviv",
    "Muscat",
    "Jerusalem",
  ],
};
